[package]
name = "gamma"
version = "0.6.0"
authors = ["The Gamma Project Developers"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/metamolecular/gamma"
description = """
Graph primitives and traversals for Rust.
"""

[dependencies]
indexmap = "1.4.0"
